name: Publish release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    name: Publish release
    if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get previous tag (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Get next SemVers (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Set hotfix version (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: echo "RELEASE_VERSION=${{ steps.semvers.outputs.patch }}" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.event.pull_request.merge_commit_sha }}
          name: Release v${{ env.RELEASE_VERSION }}
          tag: v${{ env.RELEASE_VERSION }}
          token: ${{ github.token }}

      - name: Update major/minor tags
        uses: vweevers/additional-tags-action@v1
